## joint_names
joint_names: [lwa4p_joint1, lwa4p_joint2, lwa4p_joint3, lwa4p_joint4, lwa4p_joint5, lwa4p_joint6]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - lwa4p_joint1
     - lwa4p_joint2
     - lwa4p_joint3
     - lwa4p_joint4
     - lwa4p_joint5
     - lwa4p_joint6
  constraints:
      goal_time: 15.0         # If the timestamp of the goal trajectory point is t, then following the trajectory succeeds if it reaches the goal within t +/- goal_time, and aborts otherwise.
      stopped_velocity_tolerance: 0.05
      lwa4p_joint1: {trajectory: 0.05, goal: 0.001}
      lwa4p_joint2: {trajectory: 0.05, goal: 0.001}
      lwa4p_joint3: {trajectory: 0.05, goal: 0.001}
      lwa4p_joint4: {trajectory: 0.05, goal: 0.001}
      lwa4p_joint5: {trajectory: 0.05, goal: 0.001}
      lwa4p_joint6: {trajectory: 0.05, goal: 0.001}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7


## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - lwa4p_joint1
    - lwa4p_joint2
    - lwa4p_joint3
    - lwa4p_joint4
    - lwa4p_joint5
    - lwa4p_joint6
  required_drive_mode: 1

joint_group_interpol_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - lwa4p_joint1
    - lwa4p_joint2
    - lwa4p_joint3
    - lwa4p_joint4
    - lwa4p_joint5
    - lwa4p_joint6
  required_drive_mode: 7

arm_1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint1
  required_drive_mode: 1
arm_2_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint2
  required_drive_mode: 1
arm_3_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint3
  required_drive_mode: 1
arm_4_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint4
  required_drive_mode: 1
arm_5_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint5
  required_drive_mode: 1
arm_6_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint6
  required_drive_mode: 1

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - lwa4p_joint1
    - lwa4p_joint2
    - lwa4p_joint3
    - lwa4p_joint4
    - lwa4p_joint5
    - lwa4p_joint6
  required_drive_mode: 2

arm_1_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: lwa4p_joint1
  required_drive_mode: 2
arm_2_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: lwa4p_joint2
  required_drive_mode: 2
arm_3_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: lwa4p_joint3
  required_drive_mode: 2
arm_4_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: lwa4p_joint4
  required_drive_mode: 2
arm_5_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: lwa4p_joint5
  required_drive_mode: 2
arm_6_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: lwa4p_joint6
  required_drive_mode: 2
