name: arm

defaults:
  eds_pkg: schunk_lwa4p
  eds_file: "config/Schunk_0_63.dcf"

  #the following scaling is due to 16bit value range limitation of velocity command in vl mode (2)
  vel_to_device: "rint(rad2deg(vel)*250)"
  # dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
    # "6060": "1" # initial operation mode from ros.answers
    # "604Csub1": "1" # vl dimension factor numerator
    # "604Csub2": "24000" # vl dimension factor denominator

nodes:
  lwa4p_joint1:
    id: 3
  lwa4p_joint2:
    id: 4
  lwa4p_joint3:
    id: 5
  lwa4p_joint4:
    id: 6
  lwa4p_joint5:
    id: 7
  lwa4p_joint6:
    id: 8
