joint_limits:
  lwa4p_joint1:
   has_position_limits: true
   min_position: -2.957
   max_position: 2.957
    has_velocity_limits: false
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  lwa4p_joint2:
   has_position_limits: false
   min_position: -2.957
   max_position: 2.957
    has_velocity_limits: false
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  lwa4p_joint3:
   has_position_limits: false
   min_position: -2.704
   max_position: 2.704
    has_velocity_limits: false
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  lwa4p_joint4:
   has_position_limits: false
   min_position: -2.957
   max_position: 2.957
    has_velocity_limits: false
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  lwa4p_joint5:
   has_position_limits: false
   min_position: -2.957
   max_position: 2.957
    has_velocity_limits: false
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  lwa4p_joint6:
   has_position_limits: false
   min_position: -2.957
   max_position: 2.957
    has_velocity_limits: false
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 1.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
