# Settings for ros_control control loop
hardware_control_loop:
  loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - lwa4p_joint1
    - lwa4p_joint2
    - lwa4p_joint3
    - lwa4p_joint4
    - lwa4p_joint5
    - lwa4p_joint6

# Publish all joint states ----------------------------------
joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 50

#Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - lwa4p_joint1
    - lwa4p_joint2
    - lwa4p_joint3
    - lwa4p_joint4
    - lwa4p_joint5
    - lwa4p_joint6
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.05
    lwa4p_joint1: {trajectory: 0.2, goal: 0.2}
    lwa4p_joint2: {trajectory: 0.2, goal: 0.2}
    lwa4p_joint3: {trajectory: 0.2, goal: 0.2}
    lwa4p_joint4: {trajectory: 0.2, goal: 0.2}
    lwa4p_joint5: {trajectory: 0.2, goal: 0.2}
    lwa4p_joint6: {trajectory: 0.2, goal: 0.2}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7

joint_1_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint1
  required_drive_mode: 1

joint_2_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint2
  required_drive_mode: 1

joint_3_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint3
  required_drive_mode: 1

joint_4_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint4
  required_drive_mode: 1

joint_5_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint5
  required_drive_mode: 1

joint_6_position_controller:
  type: position_controllers/JointPositionController
  joint: lwa4p_joint6
  required_drive_mode: 1

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - lwa4p_joint1
    - lwa4p_joint2
    - lwa4p_joint3
    - lwa4p_joint4
    - lwa4p_joint5
    - lwa4p_joint6
  required_drive_mode: 1
